project_id = "xfbescugwgvhoheewtxd"

[functions.bulk-load-csv]
verify_jwt = false

[functions.generate-test-data]
verify_jwt = false

[functions.predict-default-risk]
verify_jwt = false

[functions.generate-loan-pdf]
verify_jwt = false
