-- Create timestamp update function (if it doesn't exist)
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create storage bucket for loan application PDFs
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'loan_applications',
  'loan_applications',
  false,
  10485760, -- 10MB limit
  ARRAY['application/pdf']
);

-- Create storage policies for loan_applications bucket
CREATE POLICY "Authenticated users can upload PDFs"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'loan_applications' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Users can view their own PDFs"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'loan_applications' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Users can update their own PDFs"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'loan_applications' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Users can delete their own PDFs"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'loan_applications' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Create loan_applications table
CREATE TABLE public.loan_applications (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Client Identification
  SK_ID_CURR BIGINT NOT NULL,
  SK_ID_PREV BIGINT,
  community_id BIGINT,
  
  -- Current Application Contract
  NAME_CONTRACT_TYPE_x TEXT,
  
  -- Personal Information
  CODE_GENDER TEXT,
  FLAG_OWN_CAR BOOLEAN,
  FLAG_OWN_REALTY BOOLEAN,
  CNT_CHILDREN INTEGER,
  CNT_FAM_MEMBERS INTEGER,
  NAME_EDUCATION_TYPE TEXT,
  NAME_FAMILY_STATUS TEXT,
  NAME_HOUSING_TYPE TEXT,
  OCCUPATION_TYPE TEXT,
  ORGANIZATION_TYPE TEXT,
  
  -- Income & Financial Capacity
  AMT_INCOME_TOTAL NUMERIC,
  NAME_INCOME_TYPE TEXT,
  AMT_CREDIT_x NUMERIC,
  AMT_ANNUITY_x NUMERIC,
  AMT_GOODS_PRICE_x NUMERIC,
  AMT_ANNUITY_x_missing BOOLEAN DEFAULT FALSE,
  AMT_GOODS_PRICE_x_missing BOOLEAN DEFAULT FALSE,
  
  -- Application Details
  NAME_TYPE_SUITE_x TEXT,
  WEEKDAY_APPR_PROCESS_START_x TEXT,
  HOUR_APPR_PROCESS_START_x INTEGER,
  
  -- Age & Employment
  DAYS_BIRTH INTEGER,
  DAYS_EMPLOYED INTEGER,
  DAYS_REGISTRATION INTEGER,
  DAYS_ID_PUBLISH INTEGER,
  DAYS_LAST_PHONE_CHANGE INTEGER,
  
  -- Contact Information
  FLAG_MOBIL BOOLEAN,
  FLAG_EMP_PHONE BOOLEAN,
  FLAG_WORK_PHONE BOOLEAN,
  FLAG_CONT_MOBILE BOOLEAN,
  FLAG_PHONE BOOLEAN,
  FLAG_EMAIL BOOLEAN,
  
  -- Regional & Location
  REGION_POPULATION_RELATIVE BOOLEAN,
  REGION_RATING_CLIENT INTEGER,
  REGION_RATING_CLIENT_W_CITY INTEGER,
  REG_REGION_NOT_LIVE_REGION BOOLEAN,
  REG_REGION_NOT_WORK_REGION BOOLEAN,
  LIVE_REGION_NOT_WORK_REGION BOOLEAN,
  REG_CITY_NOT_LIVE_CITY BOOLEAN,
  REG_CITY_NOT_WORK_CITY BOOLEAN,
  LIVE_CITY_NOT_WORK_CITY BOOLEAN,
  URBAN_RURAL BOOLEAN,
  CITY_REGION_MISMATCH_SCORE INTEGER,
  
  -- External Data Sources
  EXT_SOURCE_2 NUMERIC,
  EXT_SOURCE_3 NUMERIC,
  EXT_SOURCE_2_missing BOOLEAN DEFAULT FALSE,
  EXT_SOURCE_3_missing BOOLEAN DEFAULT FALSE,
  
  -- Social Circle
  OBS_30_CNT_SOCIAL_CIRCLE INTEGER,
  DEF_30_CNT_SOCIAL_CIRCLE INTEGER,
  OBS_60_CNT_SOCIAL_CIRCLE INTEGER,
  DEF_60_CNT_SOCIAL_CIRCLE INTEGER,
  OBS_30_CNT_SOCIAL_CIRCLE_missing BOOLEAN DEFAULT FALSE,
  DEF_30_CNT_SOCIAL_CIRCLE_missing BOOLEAN DEFAULT FALSE,
  OBS_60_CNT_SOCIAL_CIRCLE_missing BOOLEAN DEFAULT FALSE,
  DEF_60_CNT_SOCIAL_CIRCLE_missing BOOLEAN DEFAULT FALSE,
  
  -- Credit Bureau Queries
  AMT_REQ_CREDIT_BUREAU_HOUR INTEGER,
  AMT_REQ_CREDIT_BUREAU_DAY INTEGER,
  AMT_REQ_CREDIT_BUREAU_WEEK INTEGER,
  AMT_REQ_CREDIT_BUREAU_MON INTEGER,
  AMT_REQ_CREDIT_BUREAU_QRT INTEGER,
  AMT_REQ_CREDIT_BUREAU_YEAR INTEGER,
  AMT_REQ_CREDIT_BUREAU_HOUR_missing BOOLEAN DEFAULT FALSE,
  AMT_REQ_CREDIT_BUREAU_DAY_missing BOOLEAN DEFAULT FALSE,
  AMT_REQ_CREDIT_BUREAU_WEEK_missing BOOLEAN DEFAULT FALSE,
  AMT_REQ_CREDIT_BUREAU_MON_missing BOOLEAN DEFAULT FALSE,
  AMT_REQ_CREDIT_BUREAU_QRT_missing BOOLEAN DEFAULT FALSE,
  AMT_REQ_CREDIT_BUREAU_YEAR_missing BOOLEAN DEFAULT FALSE,
  
  -- Documents Provided (Flags 2-21)
  FLAG_DOCUMENT_2 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_3 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_4 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_5 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_6 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_7 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_8 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_9 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_10 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_11 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_12 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_13 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_14 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_15 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_16 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_17 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_18 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_19 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_20 BOOLEAN DEFAULT FALSE,
  FLAG_DOCUMENT_21 BOOLEAN DEFAULT FALSE,
  
  -- Previous Application Details
  NAME_CONTRACT_TYPE_y TEXT,
  AMT_ANNUITY_y NUMERIC,
  AMT_APPLICATION NUMERIC,
  AMT_CREDIT_y NUMERIC,
  AMT_GOODS_PRICE_y NUMERIC,
  WEEKDAY_APPR_PROCESS_START_y TEXT,
  HOUR_APPR_PROCESS_START_y INTEGER,
  FLAG_LAST_APPL_PER_CONTRACT BOOLEAN,
  NFLAG_LAST_APPL_IN_DAY BOOLEAN,
  NAME_CASH_LOAN_PURPOSE TEXT,
  NAME_CONTRACT_STATUS TEXT,
  DAYS_DECISION INTEGER,
  NAME_PAYMENT_TYPE TEXT,
  CODE_REJECT_REASON TEXT,
  NAME_CLIENT_TYPE TEXT,
  NAME_GOODS_CATEGORY TEXT,
  NAME_PORTFOLIO TEXT,
  NAME_PRODUCT_TYPE TEXT,
  CHANNEL_TYPE TEXT,
  SELLERPLACE_AREA NUMERIC,
  NAME_SELLER_INDUSTRY TEXT,
  CNT_PAYMENT INTEGER,
  NAME_YIELD_GROUP TEXT,
  PRODUCT_COMBINATION TEXT,
  DAYS_FIRST_DRAWING INTEGER,
  DAYS_FIRST_DUE INTEGER,
  DAYS_LAST_DUE_1ST_VERSION INTEGER,
  DAYS_LAST_DUE INTEGER,
  DAYS_TERMINATION INTEGER,
  NFLAG_INSURED_ON_APPROVAL BOOLEAN,
  
  -- Previous Application Missing Flags
  DAYS_FIRST_DRAWING_missing BOOLEAN DEFAULT FALSE,
  DAYS_FIRST_DUE_missing BOOLEAN DEFAULT FALSE,
  DAYS_LAST_DUE_1ST_VERSION_missing BOOLEAN DEFAULT FALSE,
  DAYS_LAST_DUE_missing BOOLEAN DEFAULT FALSE,
  DAYS_TERMINATION_missing BOOLEAN DEFAULT FALSE,
  AMT_GOODS_PRICE_y_missing BOOLEAN DEFAULT FALSE,
  CNT_PAYMENT_missing BOOLEAN DEFAULT FALSE,
  AMT_ANNUITY_y_missing BOOLEAN DEFAULT FALSE,
  NFLAG_INSURED_ON_APPROVAL_missing BOOLEAN DEFAULT FALSE,
  
  -- Derived/Calculated Fields
  is_CashLoan BOOLEAN,
  CREDIT_INCOME_RATIO NUMERIC,
  ANNUITY_INCOME_RATIO NUMERIC,
  CREDIT_GOODS_RATIO NUMERIC,
  INCOME_PER_PERSON NUMERIC,
  CHILDREN_RATIO NUMERIC,
  PAYMENT_RATE NUMERIC,
  AGE_YEARS NUMERIC,
  EMPLOYED_YEARS NUMERIC,
  REGISTRATION_YEARS_AGO NUMERIC,
  ID_PUBLISH_YEARS_AGO NUMERIC,
  PHONE_CHANGE_YEARS_AGO NUMERIC,
  EMPLOYMENT_TO_AGE_RATIO NUMERIC,
  NUM_ACTIVE_CONTACTS INTEGER,
  HAS_WORK_CONTACT BOOLEAN,
  HAS_ALL_DOCS INTEGER,
  STABILITY_SCORE INTEGER,
  BUREAU_QUERY_INTENSITY INTEGER,
  SHORT_TERM_BUREAU_RATIO NUMERIC,
  CREDIT_DIFF NUMERIC,
  ANNUITY_DIFF NUMERIC,
  GOODS_PRICE_DIFF NUMERIC,
  CREDIT_TO_GOODS_DELTA_RATIO NUMERIC,
  SAME_CONTRACT_TYPE BOOLEAN,
  SAME_WEEKDAY_APPR BOOLEAN,
  HOUR_APPR_DIFF INTEGER,
  CREDIT_DURATION_DAYS INTEGER,
  TIME_TO_FIRST_PAYMENT_DAYS INTEGER,
  TIME_TO_TERMINATION_DAYS INTEGER,
  OVERLAP_WITH_CURRENT BOOLEAN,
  
  -- PDF storage path
  pdf_path TEXT,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.loan_applications ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own loan applications"
ON public.loan_applications
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own loan applications"
ON public.loan_applications
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own loan applications"
ON public.loan_applications
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own loan applications"
ON public.loan_applications
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Create indexes for performance
CREATE INDEX idx_loan_applications_user_id ON public.loan_applications(user_id);
CREATE INDEX idx_loan_applications_sk_id_curr ON public.loan_applications(SK_ID_CURR);
CREATE INDEX idx_loan_applications_created_at ON public.loan_applications(created_at DESC);
CREATE INDEX idx_loan_applications_sk_id_prev ON public.loan_applications(SK_ID_PREV);

-- Create updated_at trigger
CREATE TRIGGER update_loan_applications_updated_at
BEFORE UPDATE ON public.loan_applications
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();