// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfbescugwgvhoheewtxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmYmVzY3Vnd2d2aG9oZWV3dHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NzEzMTUsImV4cCI6MjA3NTI0NzMxNX0.XsHDz4u8UdUx-bponO54I9o69BGo4_1BwbIt78g8mpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});